export const CHANGE_SEARCH_FIELD='CHANGE_SEARCH_FIELD'

export const REQUEST_PLATFORMS_PENDING='REQUEST_PLATFORMS_PENDING';
export const REQUEST_PLATFORMS_SUCCESS='REQUEST_PLATFORMS_SUCCESS';
export const REQUEST_PLATFORMS_FAILED='REQUEST_PLATFORMS_FAILED';